/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
import * as import0 from './toast.component';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
export declare class Wrapper_ToastComponent {
    _eventHandler: Function;
    context: import0.ToastComponent;
    _changed: boolean;
    _expr_0: any;
    subscription0: any;
    constructor();
    ngOnDetach(view: import2.AppView<any>, componentView: import2.AppView<any>, el: any): void;
    ngOnDestroy(): void;
    check_toast(currValue: any, throwOnChange: boolean, forceUpdate: boolean): void;
    ngDoCheck(view: import2.AppView<any>, el: any, throwOnChange: boolean): boolean;
    checkHost(view: import2.AppView<any>, componentView: import2.AppView<any>, el: any, throwOnChange: boolean): void;
    handleEvent(eventName: string, $event: any): boolean;
    subscribe(view: import2.AppView<any>, _eventHandler: any, emit0: boolean): void;
}
export declare const ToastComponentNgFactory: import7.ComponentFactory<import0.ToastComponent>;
export declare class View_ToastComponent0 extends import2.AppView<import0.ToastComponent> {
    _text_0: any;
    _el_1: any;
    _NgClass_1_3: import8.Wrapper_NgClass;
    _text_2: any;
    _anchor_3: any;
    _vc_3: import9.ViewContainer;
    _TemplateRef_3_5: any;
    _NgIf_3_6: import10.Wrapper_NgIf;
    _text_4: any;
    _anchor_5: any;
    _vc_5: import9.ViewContainer;
    _TemplateRef_5_5: any;
    _NgIf_5_6: import10.Wrapper_NgIf;
    _text_6: any;
    _arr_14: any;
    constructor(viewUtils: import3.ViewUtils, parentView: import2.AppView<any>, parentIndex: number, parentElement: any);
    createInternal(rootSelector: string): import7.ComponentRef<any>;
    injectorGetInternal(token: any, requestNodeIndex: number, notFoundResult: any): any;
    detectChangesInternal(throwOnChange: boolean): void;
    destroyInternal(): void;
    createEmbeddedViewInternal(nodeIndex: number): import2.AppView<any>;
}
